### ISSUE TITLE
Armor Values for Dwarf, Elf, and Mithril Armor

### ISSUE THREAD

**Issue by Vestak3321** [FroztiGaming/Fantasycraft#1]
Hey I just downloaded your mod and its working great so far.  This isn't a very big issue but it's just something that I noticed.  The armor values for the chestplate and leggings are switched for the Dwarven (bronze), Elven (silver), and Mithril armor sets.  The Dwarven chestplate has 6 armor points while the leggings have 8, and the same goes for the Elven armor pieces.  The Mithril chestplate has 7 armor points and the leggings have 9.  Not a big deal, but it seems wrong.

**Comment by NickSuttonDicken** [comment]
I'll have a patch out in 5-6 hours

**Comment by NickSuttonDicken** [comment]
Resolved Armor Protection Issue
