### ISSUE TITLE
Triton Trident

### ISSUE THREAD

**Issue by Vestak3321** [FroztiGaming/Fantasycraft#2]
The name of the Triton Trident in game is Triton Triton

**Comment by FroztiGaming** [comment]
I'll have a patch out in around 5-6 hours

**Comment by FroztiGaming** [comment]
I did some testing and it's actually the Conduit Power status effect, which is given to the player through the Origins mod. Having Conduit Power V just completely removes the animation as it's too fast.

**Comment by NickSuttonDicken** [comment]
Resolved Typo Issue

**Comment by Vestak3321** [comment]
Thanks so much! looks good!
