### ISSUE TITLE
Mining Animation for Triton Origin does not Work Underwater

### ISSUE THREAD

**Issue by Vestak3321** [FroztiGaming/Fantasycraft#3]
When you pick the Triton Origin and mine with any tool or your fist while underwater, the mining animation does not show up.  All other Origins show the mining animation when underwater and on ground.

**Comment by FroztiGaming** [comment]
That's actually just a side effect of having haste too high in 1.16

**Comment by NickSuttonDicken** [comment]
I think that may actually be a bug with the Origins mod, since the Triton Origin is completely made using a datapack for Origins

**Comment by NickSuttonDicken** [comment]
Did some testing and it's actually the "Conduit Power" status effect, the default for Origins must be "Conduit Power V" which makes the mining animation so fast it just doesn't render
