### ISSUE TITLE
Mithril Full Set Bonus Regeneration only works if you have full hunger

### ISSUE THREAD

**Issue by Vestak3321** [FroztiGaming/Fantasycraft#4]
The regeneration effect gained from the mithril armor is active at all time while wearing the full set.  However, when I am hungry I do not regenerate health at all.  When I eat my fill, the regen starts working again, regenerating my health much fast than normal healing just from having a full food bar.

**Comment by NickSuttonDicken** [comment]
As it's using the vanilla regen status effect it may be how minecraft does it. But that being said I'll have a look into it and do some testing to see if that's true or if I can improve it, wouldn't want Mithril to not have a good status effect

**Comment by NickSuttonDicken** [comment]
Fixed as of the last update
